# Generated by Django 2.2.4 on 2019-10-17 12:56

import api.utils.id_generatory
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=api.utils.id_generatory.id_gen, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('transaction_id', models.PositiveIntegerField(null=True)),
                ('transaction_ref_id', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(choices=[('SS', 'Success'), ('PG', 'Pending'), ('FD', 'Failed')], default='PG', max_length=2)),
                ('financial_transaction_id', models.PositiveIntegerField(null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
