# Generated by Django 2.2.4 on 2019-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20191025_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='financial_transaction_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
